### ISSUE TITLE
alert_tests.cpp

### ISSUE THREAD

**Issue by neiros** [neiros/---TTC---#16]
Return the old vAlertPubKey from Bitcoin or change to new vAlertPubKey?

valid - https://github.com/neiros/TDC/blob/bitcoin-genesis/src/chainparams.cpp#L106
??? - https://github.com/neiros/TDC/blob/TDC/src/chainparams.cpp#L32

https://bitcointalk.org/index.php?topic=2254304.msg28780839#msg28780839

**Comment by prism-lab** [comment]
Generate the new one.
Using someone else's key is always a bad decision.
